### ISSUE TITLE
App don't show USB attached.

### ISSUE THREAD

**Issue by norani** [ianhanniballake/LocalStorage#2]
Hi, your app is perfectly works.  I develop an android app that communicate with USB. One of the button in my app is to browse file, so I integrate my app with your app. However, after integration, my app cannot detect the USB attached. 

To be clear, sometimes, it shows USB attached but not more than 2 seconds. Sometimes it never shows. If it shows and I choose a file from the USB, my app catch exception file not found.

The internal storage is working perfectly fine. For your information, I copied the `MediaAvailibilityBroadcastReceiver `and `LocalStorageProvider `class. I also put permission `WRITE_EXTERNAL_STORAGE` in Android Manifest. Not to forget, I changed `DOCUMENTS_AUTHORITY` to  my `packageName.documents`. In addition, I delete all codes that related to `OPEN IMAGES`, `CREATE A FILE` and `OPEN DIRECTORY` buttons since I only used `OPEN ALL FILES` button.

Is there any codes that I need to changed that you may think that I have missed to look for?

**Comment by ianhanniballake** [comment]
There's a built in DocumentsProvider for USB attached storage - this app is not intended to replace/duplicate that default functionality.
