### ISSUE TITLE
Missing release

### ISSUE THREAD

**Issue by IzzySoft** [ianhanniballake/LocalStorage#3]
Hi Ian,

two questions:

1. Playstore has v2.1, but here at GH in `releases/` the latest version is v2.0. Did you forget to publish it here, and will you fill that gap? Background: I was asked to include your app with [my F-Droid compatible repo](https://android.izzysoft.de/repo) – and of course I don't want to add an outdated version :)
2. Are you still working on it, i.e. is the project still "alive"? Same background, basically, as my backend automatically checks for updates. Plus even v2.1 is not "that fresh", dated 8/2015.

Thanks in advance,
Izzy.

**Comment by beeshyams** [comment]
+1. Impressive app. Thanks

**Comment by ianhanniballake** [comment]
Created [a Release 2.1 tag](https://github.com/ianhanniballake/LocalStorage/releases/tag/v2.1) - thanks for the reminder!

There's no new DocumentsProvider APIs that would affect a local storage app. As soon as there are, I would update the app.

**Comment by IzzySoft** [comment]
Thanks a lot, Ian! You can now find [LocalStorage in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.ianhanniballake.localstorage). It will be updated automatically (usually within 24h) whenever you make a new release (and attach the `.apk` to that, or course). As indicated, my repo can be used with the F-Droid client – so people who don't want (or cannot) use Playstore have an alternative :)

Thumbs up :thumbsup: and further good luck with your project!
