### ISSUE TITLE
Donate option is not working properly

### ISSUE THREAD

**Issue by saraji-ali** [ianhanniballake/LocalStorage#5]
# Project Information

* Repository:  https://github.com/ianhanniballake/LocalStorage
* Project Name: LocalStorage

# Expected behavior

I was expecting a PayPal one page to open when I click on the donate button

# Actual behavior
When I click the donate button, I do not see any opens

# How to reproduce
1-open the application
2- click on DONATE button
3- see bug 

* Browser/App version:  2.3
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190511_182133](https://user-images.githubusercontent.com/50115498/57570372-e8971100-73b5-11e9-82fa-9472ecafa7bd.gif)

# My Github Account
https://github.com/facebook-786

**Comment by ianhanniballake** [comment]
Donating via PayPal was purposefully removed in 43a96a7719a5ff1548d2482ed7afa5b882ebf036 so the only option that should appear are donating via Google Play.

Did you download Local Storage from the Google Play Store? Have you signed into a Google account on your device?

**Comment by saraji-ali** [comment]
yes, sir, I was downloaded from google play store 

My Google Play Store account already  login

**Comment by ianhanniballake** [comment]
Unfortunately, I haven't been able to reproduce this on multiple devices with multiple accounts. It is up to the Google Play Store to provide the list of in-app purchases that display in the dialog, so this is out of our control.

You could certainly try clearing data on the Google Play Store, but as there's nothing else I can do on my side, I'll close this issue.
