### ISSUE TITLE
Delete file

### ISSUE THREAD

**Issue by ernestp** [ianhanniballake/LocalStorage#6]
Seems there is no delete file option

**Comment by ianhanniballake** [comment]
We [already support deleting](https://github.com/ianhanniballake/LocalStorage/blob/master/mobile/src/main/java/com/ianhanniballake/localstorage/LocalStorageProvider.kt#L235) if we have write access to the file, so deleting should already appear when you use the Files app with Local Storage.

**Comment by ernestp** [comment]
@ianhanniballake How can I see it in UI? App in google play not allow me to delete anything.

**Comment by ianhanniballake** [comment]
As per the readme, and the [description on Google Play](https://play.google.com/store/apps/details?id=com.ianhanniballake.localstorage):

> Note that this app is not meant to be used by itself (although we do provide some sample queries), but to be used to enable other applications access to files they would normally not be able to see - you shouldn't ever need to actually open this app!

So like I said, you should be using the default file explorer app (on Pixel devices, it is called 'Files', on older devices it is often called 'Downloads') and select the 'Home' option from the side nav, as seen in the screenshots. The Files app is what calls into the APIs provided by Local Storage to let you rename, delete, copy, etc. - this isn't something that the UI in Local Storage does.
